# imagecodecs/pyproject.toml

[build-system]
requires = ["setuptools", "numpy>=2", "Cython>=3.2"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 79
target-version = ["py311", "py312", "py313"]
skip-string-normalization = true

[tool.isort]
profile = "black"
line_length = 79
